import { Button } from "@components/atoms";
import ConnectBtn from "@components/moleculas/WalletNavItem/ConnectBtn";
import { Stack } from "@mantine/core";
import {
  OperationType,
  SafeTransactionDataPartial,
} from "@safe-global/safe-core-sdk-types";
import { fetchSigner } from "@wagmi/core";
import { ethers } from "ethers";
import Head from "next/head";
import { useEffect } from "react";
import { SafeService } from "services/safeSdk";
import { useSigner } from "wagmi";

export default function Home() {
  const { data: signer } = useSigner();
  useEffect(() => {
    const initialize = async () => {
      SafeService.instance().initialize(
        signer,
        "0x775ad9c18e0d8de7dfcffc8540a0203f61b39a7e"
      );
    };
    if (signer) initialize();
  }, [signer]);

  const onCreate = async () => {
    const safe = await SafeService.instance().sdk();
    const service = await SafeService.instance().service();
    const safeAddress = ethers.utils.getAddress(
      "0x775ad9c18e0d8de7dfcffc8540a0203f61b39a7e"
    );
    const safeTransactionData: SafeTransactionDataPartial = {
      to: "0x11a9074399b103E1d3D18e63359D35541fe05b55",
      value: "1", // 1 wei
      data: "0x",
      operation: OperationType.Call,
    };
    const safeTransaction = await safe.createTransaction({
      safeTransactionData,
    });
    console.log("- safeAddress:", safeAddress);
    console.log("- safeTransaction:", safeTransaction);

    const senderAddress = await signer!.getAddress();
    console.log("- senderAddress:", senderAddress);
    const safeTxHash = await safe.getTransactionHash(safeTransaction);
    console.log("- safeTxHash:", safeTxHash);
    const signature = await safe.signTransactionHash(safeTxHash);
    console.log("- signature:", signature);

    // Propose transaction to the service
    await service.proposeTransaction({
      safeAddress,
      safeTransactionData: safeTransaction.data,
      safeTxHash,
      senderAddress,
      senderSignature: signature.data,
    });
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Stack
          mt={56}
          sx={{
            marginInline: "auto",
          }}
          align="center"
        >
          <Button onClick={onCreate}>Create tx</Button>
        </Stack>
      </main>
    </>
  );
}
