import ConnectBtn from "@components/moleculas/WalletNavItem/ConnectBtn";
import { Stack } from "@mantine/core";
import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Stack
          mt={56}
          sx={{
            marginInline: "auto",
          }}
          align="center"
        >
          <ConnectBtn />
        </Stack>
      </main>
    </>
  );
}
